name: Build, Tag and Push Container Images to GAR Repository

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
  push:
    branches:
      - master
    tags:
      - '**'
  workflow_dispatch: {}

jobs:
  build-and-push-autoconnect:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'pull_request' &&
        contains(github.event.pull_request.labels.*.name, 'preview') &&
        github.event.pull_request.head.repo.full_name == github.repository
      )
    permissions:
      contents: read
      id-token: write
    uses: mozilla-it/deploy-actions/.github/workflows/build-and-push.yml@4784cb70739a4f32ce010921f60fb1ebbc791a38 # v6.2.2
    with:
      image_name: autoconnect
      gar_name: autopush-prod
      project_id: moz-fx-autopush-prod
      postbuild_script: "./scripts/smoketests/autoconnect.sh autoconnect"
      docker_build_args: |
        CRATE=autoconnect
        BINARY=autoconnect

  build-and-push-autoendpoint:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'pull_request' &&
        contains(github.event.pull_request.labels.*.name, 'preview') &&
        github.event.pull_request.head.repo.full_name == github.repository
      )
    permissions:
      contents: read
      id-token: write
    uses: mozilla-it/deploy-actions/.github/workflows/build-and-push.yml@4784cb70739a4f32ce010921f60fb1ebbc791a38 # v6.2.2
    with:
      image_name: autoendpoint
      gar_name: autopush-prod
      project_id: moz-fx-autopush-prod
      postbuild_script: "./scripts/smoketests/autoendpoint.sh autoendpoint"
      docker_build_args: |
        CRATE=autoendpoint
        BINARY=autoendpoint

  build-and-push-enterprise:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (
        github.event_name == 'push' &&
        (github.ref_name == 'master' || startsWith(github.ref, 'refs/tags/'))
      ) ||
      (
        github.event_name == 'pull_request' &&
        contains(github.event.pull_request.labels.*.name, 'preview') &&
        github.event.pull_request.head.repo.full_name == github.repository
      )
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-build-and-push
        id: setup
        with:
          workload_identity_provider: ${{ vars.GCPV2_GITHUB_WORKLOAD_IDENTITY_PROVIDER }}
          gcp_service_account: "${{ vars.SERVICE_ACCOUNT_NAME || 'artifact-writer' }}@moz-fx-fx-enterprise-prod.iam.gserviceaccount.com"

      - name: Compute autoconnect tags
        run: |
          TAGS=$(cat <<EOF
          us-docker.pkg.dev/moz-fx-fx-enterprise-prod/fx-enterprise-private/autoconnect:${{ steps.setup.outputs.image_tag }}
          EOF
          )
          if [[ "${{ steps.setup.outputs.push_latest }}" == "true" ]]; then
            TAGS="$TAGS
          us-docker.pkg.dev/moz-fx-fx-enterprise-prod/fx-enterprise-private/autoconnect:latest_enterprise"
          fi
          echo "IMAGE_TAGS<<EOF" >> "$GITHUB_ENV"
          echo "$TAGS" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

      - name: Build and push autoconnect to enterprise GAR
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          push: true
          build-args: |
            CRATE=autoconnect
            BINARY=autoconnect
            BUILD_ARGS=--no-default-features --features=enterprise
          tags: ${{ env.IMAGE_TAGS }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Compute autoendpoint tags
        run: |
          TAGS=$(cat <<EOF
          us-docker.pkg.dev/moz-fx-fx-enterprise-prod/fx-enterprise-private/autoendpoint:${{ steps.setup.outputs.image_tag }}
          EOF
          )
          if [[ "${{ steps.setup.outputs.push_latest }}" == "true" ]]; then
            TAGS="$TAGS
          us-docker.pkg.dev/moz-fx-fx-enterprise-prod/fx-enterprise-private/autoendpoint:latest_enterprise"
          fi
          echo "IMAGE_TAGS<<EOF" >> "$GITHUB_ENV"
          echo "$TAGS" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"

      - name: Build and push autoendpoint to enterprise GAR
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        with:
          context: .
          push: true
          build-args: |
            CRATE=autoendpoint
            BINARY=autoendpoint
            BUILD_ARGS=--no-default-features --features=enterprise
          tags: ${{ env.IMAGE_TAGS }}
          cache-from: type=gha
